# Generated by Django 4.2.7 on 2025-11-23 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('question', models.CharField(help_text='The prediction question', max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('resolution', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(help_text='When the market closes for trading')),
                ('resolution_date', models.DateTimeField(blank=True, help_text='When the market was resolved', null=True)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_liquidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('yes_price', models.DecimalField(decimal_places=4, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('no_price', models.DecimalField(decimal_places=4, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='markets.market')),
            ],
        ),
    ]
