# Generated by Django 4.2.7 on 2025-11-23 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_markets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', '-created_at'], name='markets_mar_status_f5bebe_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['category', '-created_at'], name='markets_mar_categor_d546f4_idx'),
        ),
    ]
