# Generated by Django 4.2.7 on 2025-11-23 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('order_type', models.CharField(choices=[('limit', 'Limit'), ('market', 'Market')], default='limit', max_length=10)),
                ('price', models.DecimalField(decimal_places=4, help_text='Price per share (0.00 to 1.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of shares', max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('partial', 'Partially Filled')], default='pending', max_length=20)),
                ('filled_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('no_shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('yes_avg_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('no_avg_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_trades', to='trading.order')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
