# Generated by Django 4.2.7 on 2025-11-23 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('markets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='markets.market'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_trades', to='trading.order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='markets.market'),
        ),
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='markets.market'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market', '-executed_at'], name='trading_tra_market__5966f0_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['buyer', '-executed_at'], name='trading_tra_buyer_i_a90c19_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['seller', '-executed_at'], name='trading_tra_seller__ee14a1_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', '-updated_at'], name='trading_pos_user_id_1dfbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['market'], name='trading_pos_market__8c3ea3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('user', 'market')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', 'status', 'side', 'price'], name='trading_ord_market__278ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='trading_ord_user_id_ca9b05_idx'),
        ),
    ]
