# Generated by Django 4.2.7 on 2026-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_credits_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accuracy_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate percentage (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='best_win_streak',
            field=models.IntegerField(default=0, help_text='All-time best win streak'),
        ),
        migrations.AddField(
            model_name='user',
            name='markets_predicted_correctly',
            field=models.IntegerField(default=0, help_text='Total markets where prediction was correct'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Points earned this month (resets monthly)', max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Return on investment percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='total_markets_traded',
            field=models.IntegerField(default=0, help_text='Total markets user has traded in'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total points for leaderboard ranking', max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Points earned this week (resets weekly)', max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='win_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive correct predictions'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mpesa_number',
            field=models.CharField(blank=True, help_text='M-Pesa phone number (for future use)', max_length=20),
        ),
    ]
